name: Hello World Workflow
on:
  push:
  workflow_dispatch:
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World action
        uses: sarisia/actions-repo-mig-test@main
